### ISSUE TITLE
Add checking that disk has enough space for the output directory

### ISSUE THREAD

**Issue by hrrmsn** [hrrmsn/ffcleaner#33]
Checking should be performed before starting to clean.

**Comment by hrrmsn** [comment]
It's necessary to read articles.
http://stackoverflow.com/questions/51658/cross-platform-space-remaining-on-volume-using-python/2372171#2372171
https://docs.python.org/2/library/ctypes.html
https://habrahabr.ru/post/157537/

**Comment by hrrmsn** [comment]
Test case is here. I launched script on the USB flash card with about 80mb free memory.

```
[2017-17-02 13:24:40] 2 files found.
[2017-17-02 13:24:40] Started cleaning.
[2017-17-02 13:24:40] 50% complete
[2017-17-02 13:25:09] Error when cleaning directory: 'h:\01\photos-from-self-dev'.
[2017-17-02 13:25:09] Traceback (most recent call last):
  File "E:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 477, in main
    plungedir(cleandir, todir, cleandir_files_number, ext_to_filetype, {}, unknown_exts)
  File "E:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 212, in plungedir
    cleanfile(fullpath, todir, ftype, filenames_storage)
  File "E:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 181, in cleanfile
    shutil.copy2(filepath, fulldest)
  File "E:\Program Files\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "E:\Program Files\Python27\lib\shutil.py", line 84, in copyfile
    copyfileobj(fsrc, fdst)
  File "E:\Program Files\Python27\lib\shutil.py", line 52, in copyfileobj
    fdst.write(buf)
IOError: [Errno 28] No space left on device

[2017-17-02 13:25:09] Creating archive with the log file...
[2017-17-02 13:25:09] End logging.
```

**Comment by hrrmsn** [comment]
**DONE.**
