### ISSUE TITLE
'WindowsError: [Error 145]' when deleting cleaned directory

### ISSUE THREAD

**Issue by hrrmsn** [hrrmsn/ffcleaner#39]
Full stack trace is here.

```
[2017-19-02 15:23:21] Start logging.
[2017-19-02 15:23:21] OS is Windows.
[2017-19-02 15:23:21] Platform info: Windows-XP-5.1.2600-SP3.
[2017-19-02 15:23:21] Launch command: E:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py --todir ../ffcleaner-sandbox/files_cleaned ../ffcleaner-sandbox/files.
[2017-19-02 15:23:21] Dir to output: '../ffcleaner-sandbox/files_cleaned'.
[2017-19-02 15:23:21] Dir to clean: '../ffcleaner-sandbox/files'.
[2017-19-02 15:23:21] Counting files to clean...
[2017-19-02 15:23:21] 968 files found.
[2017-19-02 15:23:22] Dir to output already exists. Do you want to overwrite it? (y/n) y
[2017-19-02 15:23:22] Removing: '../ffcleaner-sandbox/files_cleaned'...
[2017-19-02 15:23:23] Error when removing directory: '../ffcleaner-sandbox/files_cleaned'.
[2017-19-02 15:23:23] Traceback (most recent call last):
  File "E:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 351, in overwrite
    shutil.rmtree(path, onerror=remove_readonly)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "E:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 341, in remove_readonly
    func(path)
WindowsError: [Error 145] : '../ffcleaner-sandbox/files_cleaned\\unknown\\dta'

[2017-19-02 15:23:23] Creating archive with the log file...
[2017-19-02 15:23:23] End logging.
```

**Comment by hrrmsn** [comment]
Another full stack trace.

```
[2017-11-03 10:08:57] Start logging.
[2017-11-03 10:08:57] OS is Windows.
[2017-11-03 10:08:57] Platform info: Windows-XP-5.1.2600-SP3.
[2017-11-03 10:08:57] Launch command: C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py --todir ../ffcleaner-sandbox/trash_cleaned ../ffcleaner-sandbox/trash 1000000.
[2017-11-03 10:08:57] Dir to output: '../ffcleaner-sandbox/trash_cleaned'.
[2017-11-03 10:08:57] Dir to clean: '../ffcleaner-sandbox/trash'.
[2017-11-03 10:08:57] Counting files to clean...
[2017-11-03 10:08:57] 216 files found. (229.4 MB)
[2017-11-03 10:08:58] Dir to output already exists. Do you want to overwrite it? (y/n) y
[2017-11-03 10:08:58] Removing '../ffcleaner-sandbox/trash_cleaned'...
[2017-11-03 10:08:58] Error when removing directory: '../ffcleaner-sandbox/trash_cleaned'.
[2017-11-03 10:08:58] Traceback (most recent call last):
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 464, in overwrite
    shutil.rmtree(path, onerror=remove_readonly)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 454, in remove_readonly
    func(path)
WindowsError: [Error 145] : '../ffcleaner-sandbox/trash_cleaned\\document\\pdf'

[2017-11-03 10:08:58] Creating archive with the log file...
[2017-11-03 10:08:58] End logging.
```

**Comment by hrrmsn** [comment]
Another yet case of exception.

```
[2017-13-03 13:01:08] Start logging.
[2017-13-03 13:01:08] OS is Windows.
[2017-13-03 13:01:08] Platform info: Windows-XP-5.1.2600-SP3.
[2017-13-03 13:01:08] Launch command: C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py --todir ../ffcleaner-sandbox/trash_cleaned ../ffcleaner-sandbox/trash 100000.
[2017-13-03 13:01:08] Dir to output: '../ffcleaner-sandbox/trash_cleaned'.
[2017-13-03 13:01:08] Dir to clean: '../ffcleaner-sandbox/trash'.
[2017-13-03 13:01:08] Counting files to clean...
[2017-13-03 13:01:08] 216 files found. (229.4 MB)
[2017-13-03 13:01:08] Dir to output already exists. Do you want to overwrite it? (y/n) y
[2017-13-03 13:01:08] Removing '../ffcleaner-sandbox/trash_cleaned'...
[2017-13-03 13:01:08] Error when removing directory: '../ffcleaner-sandbox/trash_cleaned'.
[2017-13-03 13:01:08] Traceback (most recent call last):
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 464, in overwrite
    shutil.rmtree(path, onerror=remove_readonly)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 454, in remove_readonly
    func(path)
WindowsError: [Error 145] : '../ffcleaner-sandbox/trash_cleaned\\document\\pdf'

[2017-13-03 13:01:08] Creating archive with the log file...
[2017-13-03 13:01:08] End logging.
```

**Comment by hrrmsn** [comment]
And another yet case of error.
( :

```
[2017-13-03 13:30:20] Start logging.
[2017-13-03 13:30:20] OS is Windows.
[2017-13-03 13:30:20] Platform info: Windows-XP-5.1.2600-SP3.
[2017-13-03 13:30:20] Launch command: C:\!Plan9\dev\languages\python\ffcleaner-sandbox\$old_ffcleaner\ffcleaner.py --todir ../trash_cleaned ../trash.
[2017-13-03 13:30:20] Dir to output: '../trash_cleaned'.
[2017-13-03 13:30:20] Dir to clean: '../trash'.
[2017-13-03 13:30:20] Counting files to clean...
[2017-13-03 13:30:20] 216 files found.
[2017-13-03 13:30:21] Dir to output already exists. Do you want to overwrite it? (y/n) y
[2017-13-03 13:30:21] Removing: '../trash_cleaned'...
[2017-13-03 13:30:21] Error when removing directory: '../trash_cleaned'.
[2017-13-03 13:30:21] Traceback (most recent call last):
  File "C:\!Plan9\dev\languages\python\ffcleaner-sandbox\$old_ffcleaner\ffcleaner.py", line 358, in overwrite
    shutil.rmtree(path, onerror=remove_readonly)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "E:\Program Files\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\!Plan9\dev\languages\python\ffcleaner-sandbox\$old_ffcleaner\ffcleaner.py", line 348, in remove_readonly
    func(path)
WindowsError: [Error 145] : '../trash_cleaned\\document\\pdf'

[2017-13-03 13:30:21] Creating archive with the log file...
[2017-13-03 13:30:21] End logging.
```
