### ISSUE TITLE
IOError: [Errno 13] Permission denied (when cleaning directory)

### ISSUE THREAD

**Issue by hrrmsn** [hrrmsn/ffcleaner#44]
Script's log is below.
```

[2017-16-03 14:24:25] Start logging.
[2017-16-03 14:24:25] OS is Windows.
[2017-16-03 14:24:25] Platform info: Windows-XP-5.1.2600-SP3.
[2017-16-03 14:24:25] Launch command: C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py --todir c:\ffcleaner_sandbox\all_cleaned i:\all.
[2017-16-03 14:24:25] Dir to output: 'c:\ffcleaner_sandbox\all_cleaned'.
[2017-16-03 14:24:25] Dir to clean: 'i:\all'.
[2017-16-03 14:24:25] Counting files to clean...
[2017-16-03 14:24:45] 12306 files found. (13.6 GB)
[2017-16-03 14:25:16] Dir to output already exists. Do you want to overwrite it? (y/n) y
[2017-16-03 14:25:16] Removing 'c:\ffcleaner_sandbox\all_cleaned'...
[2017-16-03 14:25:18] Ok.
[2017-16-03 14:25:18] Started cleaning. (b_size is 1.0 MB)
[2017-16-03 14:25:41] Traceback (most recent call last):
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 631, in main
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 304, in plungedir
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 304, in plungedir
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 304, in plungedir
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 304, in plungedir
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 304, in plungedir
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 304, in plungedir
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 304, in plungedir
    copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 308, in plungedir
    cleanfile(fullpath, todir, ftype, filenames_storage, cleandir_size, copybytes_buffer_size)
  File "C:\!Plan9\dev\languages\python\ffcleaner\ffcleaner.py", line 280, in cleanfile
    shutil.copy2(filepath, fulldest)
  File "E:\Program Files\Python27\lib\shutil.py", line 130, in copy2
    copyfile(src, dst)
  File "E:\Program Files\Python27\lib\shutil.py", line 83, in copyfile
    with open(dst, 'wb') as fdst:
IOError: [Errno 13] Permission denied: 'c:\\ffcleaner_sandbox\\all_cleaned\\image\\jpg\\\xd0\xe8\xf1\xf3\xed\xee\xea 1(2).JPG'

[2017-16-03 14:25:41] Creating archive with the log file...
[2017-16-03 14:25:41] End logging.
```

I found that problem file has following path.
`i:\all\1\Остальное\Прошлое\Свалка\Резервная копия курсового\№4\Расчетно-пояснительная записка\Рисунок 1.JPG`

And after coping it has at some reason read-only property. Any ideas?

**Comment by hrrmsn** [comment]
Usefull link.
http://stackoverflow.com/questions/33618656/python-windowserror-error-123-the-filename-directory-name-or-volume-label-s

Learn more about python _raw string_. I think it's will help me better understand the issue.

**Comment by hrrmsn** [comment]
I have an idea. Some symbols from path is treated wrong. For example consider the following path.
`file_path = 'c:\dir\subdir\xc1\xe5\xe7\xfb\xec\xff\xed\xed\xfb\xe9.png'`

Obviously that some slashes uses as real slashes, but some uses for encode nonstandard symbols.

**Comment by hrrmsn** [comment]
I understood the problem. Yeah! My script was trying to replace existing file with set up `read-only` property.
( :

Now it's time to learn why it happens.

**Comment by hrrmsn** [comment]
I created zip [file](https://github.com/hrrmsn/ffcleaner/files/852370/ffc_test.zip) with test case.

**Comment by hrrmsn** [comment]
The problem was in the algorithm of `filename_storage` dictionary creation. Now `basename` variable couldn't contain extension with the uppercase letters.

For instance such filenames were treated as the different: `pict1.jpg` and `pic1.JPG`.

**Comment by hrrmsn** [comment]
**DONE.**
